### ISSUE TITLE
Loader: Illegal base64 character 2e

### ISSUE THREAD

**Issue by turbaszek** [snowplow-incubator/snowplow-bigquery-loader#112]
Hi all,

I am trying to run bigquery loader as k8s job:
```yml
...
containers:
        - image: snowplow-docker-registry.bintray.io/snowplow/snowplow-bigquery-loader:0.5.0
          imagePullPolicy: IfNotPresent
          name: bq-loader
          args:
            - --config=/snowplow/customconfig/config/production.conf
            - --resolver=/snowplow/customconfig/resolver/resolver.json
...
```
I configured the topis/subscriptions as per https://docs.snowplowanalytics.com/docs/setup-snowplow-on-gcp/setup-bigquery-destination/bigquery-loader-0-5-0/#topics-and-message-formats

However, there's an error with no stack trace:
```
{
 insertId:  "g4r5w3es15d1dlm7e"   
 labels: {…}   
 logName:  "projects/PROJECT/logs/stderr"   
 receiveTimestamp:  "2020-07-12T11:58:09.421811185Z"   
 resource: {
  labels: {…}    
  type:  "k8s_container"    
 }
 severity:  "ERROR"   
 textPayload:  "Illegal base64 character 2e
"   
 timestamp:  "2020-07-12T11:57:57.447664061Z"   
}
```

Any ideas what can cause it?
