### ISSUE TITLE
Project ID is required for this service

### ISSUE THREAD

**Issue by ArcLightSlavik** [snowplow-incubator/snowplow-bigquery-loader#171]
docker-compose.yml
```
  mutator:
    image: gcr.io/snowplow-308015/mutator:20.3.1
    build:
      context: services/mutator
    entrypoint: ["sh", "/config/mutator.sh"]
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/vmagent/services/mutator/credentials.json
    volumes:
      - ./services/mutator/mutator-config:/config
      - ./services/mutator:/home/vmagent/services/mutator
```

Dockerfile
```
# mutator

FROM snowplow/snowplow-bigquery-mutator:0.6.2

COPY mutator-config/bigquery_config.json /config/bigquery_config.json
COPY mutator-config/iglu_resolver.json /config/iglu_resolver.json
COPY mutator-config/mutator.sh /config/mutator.sh

RUN chmod +x /config/mutator.sh
```

bigquery_config.json
```
{
    "schema": "iglu:com.snowplowanalytics.snowplow.storage/bigquery_config/jsonschema/1-0-0",
    "data": {
        "name": "Snowplow clicks",
        "id": "dc345bdd-409d-4572-88f4-bdc80bc2e30a",

        "projectId": "snowplow-308015",
        "datasetId": "platform",
        "tableId": "clicks",

        "input": "clicks-enriched-good-sub",
        "typesTopic": "clicks-bq-types",
        "typesSubscription": "clicks-bq-types-sub",
        "badRows": "clicks-bq-bad-rows",
        "failedInserts": "clicks-bq-failed-inserts",

        "load": {
            "mode": "STREAMING_INSERTS",
            "retry": false
        },

        "purpose": "ENRICHED_EVENTS"
    }
}
```

```
#!/bin/bash

echo "LISTENING"
./bin/snowplow-bigquery-mutator listen --config $(cat /config/bigquery_config.json | base64 -w 0) --resolver $(cat /config/iglu_resolver.json | base64 -w 0)
```

Results in:
```
mutator_1    | LISTENING
mutator_1    | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
mutator_1    | SLF4J: Defaulting to no-operation (NOP) logger implementation
mutator_1    | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
mutator_1    | java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
```

I assume this was a change introduced in this commit -> https://github.com/snowplow-incubator/snowplow-bigquery-loader/commit/6a2ad43d8db150c27ebc94ed2f84a6b850922d54

But <https://docs.snowplowanalytics.com/docs/getting-started-on-snowplow-open-source/setup-snowplow-on-gcp/setup-bigquery-destination/bigquery-loader-0-6-0/> does not have a way to pass the projectId
